SELECT
  ?item
  ?itemLabel
  (SAMPLE(?descriptionValue) AS ?description)
  (MIN(?yearValue) AS ?year)
  (SAMPLE(?countryLabelValue) AS ?countryLabel)
  ?sitelinks WHERE {
  VALUES ?class {
    wd:Q15661340 # ancient city
    wd:Q148837 # polis
    wd:Q133442 # city-state
    wd:Q486972 # human settlement
    wd:Q515 # city
    wd:Q532 # village
    wd:Q1708422 # settlement site
    wd:Q65064889 # Bronze Age settlement
    wd:Q106491339 # Neolithic settlement
    wd:Q7251867 # proto-city
    wd:Q22674925 # former settlement
    wd:Q707813 # Hanseatic city
    wd:Q69391739 # Greek colony
    wd:Q2202509 # Roman city
    wd:Q106468588 # Jewish settlement in the land of Israel
    wd:Q7830262 # township of Myanmar
    wd:Q16124843 # municipality of Libya
    wd:Q125366925 # village in Egypt
    wd:Q755017 # tell
    wd:Q3024240 # historical country
    wd:Q3914 # school
    wd:Q504400 # gymnasium
  }
  ?item
    wdt:P31 ?class;
    wdt:P571 ?date;
    wikibase:sitelinks ?sitelinks;
    rdfs:label ?itemLabel.
  FILTER NOT EXISTS { ?item wdt:P1619 ?openingDate. }
  FILTER EXISTS {
    VALUES ?historicClass {
      wd:Q839954 # archaeological site
      wd:Q15661340 # ancient city
      wd:Q148837 # polis
      wd:Q133442 # city-state
      wd:Q1708422 # settlement site
      wd:Q65064889 # Bronze Age settlement
      wd:Q106491339 # Neolithic settlement
      wd:Q7251867 # proto-city
      wd:Q69391739 # Greek colony
      wd:Q2202509 # Roman city
      wd:Q3024240 # historical country
      wd:Q755017 # tell
    }
    ?item wdt:P31 ?historicClass.
  }
  FILTER(LANG(?itemLabel) = "en")
  OPTIONAL {
    ?item schema:description ?descriptionValue.
    FILTER(LANG(?descriptionValue) = "en")
  }
  OPTIONAL {
    ?item wdt:P17 ?country.
    ?country rdfs:label ?countryLabelValue.
    FILTER(LANG(?countryLabelValue) = "en")
  }
  BIND(YEAR(?date) AS ?yearValue)
  FILTER(?sitelinks >= 40)
}
GROUP BY ?item ?itemLabel ?sitelinks
ORDER BY DESC(?sitelinks)
LIMIT 500
