SELECT ?item ?itemLabel ?description (MIN(?yearValue) AS ?year) ?sitelinks WHERE {
  ?item
    wdt:P31/wdt:P279* wd:Q16323605; # food brand
    wdt:P571|wdt:P577 ?date;
    wikibase:sitelinks ?sitelinks;
    rdfs:label ?itemLabel;
    schema:description ?description.

  FILTER(LANG(?itemLabel) = "en")
  FILTER(LANG(?description) = "en")
  FILTER(?sitelinks >= 5)

  BIND(YEAR(?date) AS ?yearValue)
}
GROUP BY ?item ?itemLabel ?description ?sitelinks
ORDER BY DESC(?sitelinks)
LIMIT 500
